/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Activity {
  app_id: string;
  body: string | null;
  external_id: string | null;
  icon: string | null;
  id: number;
  login_name: string;
  module_id: number;
  portlet_params: string | null;
  priority: number | null;
  title: string;
  update_date: Timestamp | null;
}

export interface ActivityMap {
  activity_id: number | null;
  id: number;
  is_read: number | null;
  login_name: string;
}

export interface AipoLicense {
  license: string;
  license_id: Generated<number>;
  limit_users: number | null;
}

export interface AppData {
  app_id: string;
  id: number;
  login_name: string;
  name: string;
  value: string | null;
}

export interface Application {
  app_id: string;
  consumer_key: string | null;
  consumer_secret: string | null;
  create_date: Timestamp | null;
  description: string | null;
  icon: string | null;
  icon64: string | null;
  id: number;
  status: number | null;
  summary: string | null;
  title: string | null;
  update_date: Timestamp | null;
  url: string;
}

export interface ContainerConfig {
  id: number;
  name: string;
  value: string | null;
}

export interface EipFacilityGroup {
  facility_id: number;
  group_id: number;
  id: Generated<number>;
}

export interface EipMAddressbook {
  address_id: Generated<number>;
  cellular_mail: string | null;
  cellular_phone: string | null;
  company_id: number | null;
  create_date: Timestamp | null;
  create_user_id: number | null;
  email: string | null;
  first_name: string | null;
  first_name_kana: string | null;
  last_name: string | null;
  last_name_kana: string | null;
  note: string | null;
  owner_id: number | null;
  position_name: string | null;
  public_flag: string | null;
  telephone: string | null;
  update_date: Timestamp | null;
  update_user_id: number | null;
}

export interface EipMAddressbookCompany {
  address: string | null;
  company_id: Generated<number>;
  company_name: string;
  company_name_kana: string | null;
  create_date: Timestamp | null;
  create_user_id: number | null;
  fax_number: string | null;
  post_name: string | null;
  telephone: string | null;
  update_date: Timestamp | null;
  update_user_id: number | null;
  url: string | null;
  zipcode: string | null;
}

export interface EipMAddressGroup {
  create_date: Timestamp | null;
  group_id: Generated<number>;
  group_name: string;
  owner_id: number | null;
  public_flag: string | null;
  update_date: Timestamp | null;
}

export interface EipMCompany {
  address: string | null;
  company_id: Generated<number>;
  company_name: string;
  company_name_kana: string | null;
  create_date: Timestamp | null;
  fax_number: string | null;
  ipaddress: string | null;
  ipaddress_internal: string | null;
  port: number | null;
  port_internal: number | null;
  telephone: string | null;
  update_date: Timestamp | null;
  url: string | null;
  zipcode: string | null;
}

export interface EipMConfig {
  id: number;
  name: string | null;
  value: string | null;
}

export interface EipMFacility {
  create_date: Timestamp | null;
  facility_id: Generated<number>;
  facility_name: string;
  note: string | null;
  sort: number | null;
  update_date: Timestamp | null;
  /**
   * 不使用
   */
  user_id: number;
}

export interface EipMFacilityGroup {
  group_id: Generated<number>;
  group_name: string | null;
}

export interface EipMFacilityGroupMap {
  facility_id: number | null;
  group_id: number | null;
  id: Generated<number>;
}

export interface EipMInactiveApplication {
  id: number;
  name: string | null;
}

export interface EipMMailAccount {
  account_id: Generated<number>;
  account_name: string;
  account_type: string | null;
  auth_receive_flg: number | null;
  auth_send_flg: number | null;
  auth_send_user_id: string | null;
  auth_send_user_passwd: Buffer | null;
  create_date: Timestamp | null;
  default_folder_id: number | null;
  del_at_pop3_before_days: number | null;
  del_at_pop3_before_days_flg: string | null;
  del_at_pop3_flg: string | null;
  last_received_date: Timestamp | null;
  mail_address: string;
  mail_user_name: string | null;
  non_received_flg: string | null;
  pop3_encryption_flg: number | null;
  pop3_port: string;
  pop3password: Buffer;
  pop3server_name: string;
  pop3user_name: string;
  signature: string | null;
  smtp_encryption_flg: number | null;
  smtp_port: string;
  smtpserver_name: string;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipMMailNotifyConf {
  create_date: Timestamp | null;
  notify_flg: number;
  notify_id: Generated<number>;
  notify_time: string | null;
  notify_type: number;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipMPosition {
  create_date: Timestamp | null;
  position_id: Generated<number>;
  position_name: string;
  update_date: Timestamp | null;
}

export interface EipMPost {
  /**
   * 不使用
   */
  address: string | null;
  /**
   * 不使用
   */
  company_id: number;
  create_date: Timestamp | null;
  /**
   * 不使用
   */
  fax_number: string | null;
  group_name: string | null;
  /**
   * 不使用
   */
  in_telephone: string | null;
  /**
   * 不使用
   */
  out_telephone: string | null;
  post_id: Generated<number>;
  post_name: string;
  update_date: Timestamp | null;
  /**
   * 不使用
   */
  zipcode: string | null;
}

export interface EipMUserPosition {
  id: Generated<number>;
  position: number | null;
  user_id: number | null;
}

export interface EipTAclMap {
  acl_id: Generated<number>;
  feature: string | null;
  id: number;
  level: number;
  target_id: number;
  target_type: string | null;
  type: string | null;
}

export interface EipTAclPortletFeature {
  acl_type: number | null;
  feature_alias_name: string | null;
  feature_id: Generated<number>;
  feature_name: string | null;
}

export interface EipTAclRole {
  acl_type: number | null;
  create_date: Timestamp | null;
  feature_id: number;
  note: string | null;
  role_id: Generated<number>;
  role_name: string;
  update_date: Timestamp | null;
}

export interface EipTAclUserRoleMap {
  id: Generated<number>;
  role_id: number;
  user_id: number;
}

export interface EipTAddressbookGroupMap {
  address_id: number;
  group_id: number;
  id: Generated<number>;
}

export interface EipTBlog {
  blog_id: Generated<number>;
  create_date: Timestamp | null;
  owner_id: number;
  update_date: Timestamp | null;
}

export interface EipTBlogComment {
  comment: string | null;
  comment_id: Generated<number>;
  create_date: Timestamp | null;
  entry_id: number;
  owner_id: number;
  update_date: Timestamp | null;
}

export interface EipTBlogEntry {
  allow_comments: string | null;
  blog_id: number;
  create_date: Timestamp | null;
  entry_id: Generated<number>;
  note: string | null;
  owner_id: number;
  thema_id: number | null;
  title: string;
  update_date: Timestamp | null;
}

export interface EipTBlogFile {
  create_date: Timestamp | null;
  entry_id: number;
  file_id: Generated<number>;
  file_path: string;
  file_thumbnail: Buffer | null;
  owner_id: number;
  title: string;
  update_date: Timestamp | null;
}

export interface EipTBlogFootmarkMap {
  blog_id: number;
  create_date: Timestamp;
  id: Generated<number>;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipTBlogThema {
  create_date: Timestamp | null;
  create_user_id: number;
  description: string | null;
  thema_id: Generated<number>;
  thema_name: string;
  update_date: Timestamp | null;
  update_user_id: number;
}

export interface EipTCabinetFile {
  counter: number | null;
  create_date: Timestamp | null;
  create_user_id: number | null;
  file_id: Generated<number>;
  file_name: string;
  file_path: string;
  file_size: Int8 | null;
  file_title: string;
  folder_id: number;
  note: string | null;
  update_date: Timestamp | null;
  update_user_id: number | null;
}

export interface EipTCabinetFolder {
  create_date: Timestamp | null;
  create_user_id: number | null;
  folder_id: Generated<number>;
  folder_name: string;
  note: string | null;
  parent_id: number;
  public_flag: string | null;
  update_date: Timestamp | null;
  update_user_id: number | null;
}

export interface EipTCabinetFolderMap {
  folder_id: number | null;
  id: Generated<number>;
  status: string | null;
  user_id: number | null;
}

export interface EipTCommonCategory {
  common_category_id: Generated<number>;
  create_date: Timestamp | null;
  create_user_id: number;
  name: string;
  note: string | null;
  update_date: Timestamp | null;
  update_user_id: number;
}

export interface EipTEventlog {
  create_date: Timestamp | null;
  entity_id: number | null;
  event_date: Timestamp | null;
  event_type: number | null;
  eventlog_id: Generated<number>;
  ip_addr: string | null;
  note: string | null;
  portlet_type: number | null;
  update_date: Timestamp | null;
  user_id: number | null;
}

export interface EipTExtTimecard {
  clock_in_time: Timestamp | null;
  clock_out_time: Timestamp | null;
  comeback_time1: Timestamp | null;
  comeback_time2: Timestamp | null;
  comeback_time3: Timestamp | null;
  comeback_time4: Timestamp | null;
  comeback_time5: Timestamp | null;
  create_date: Timestamp | null;
  outgoing_time1: Timestamp | null;
  outgoing_time2: Timestamp | null;
  outgoing_time3: Timestamp | null;
  outgoing_time4: Timestamp | null;
  outgoing_time5: Timestamp | null;
  punch_date: Timestamp | null;
  reason: string | null;
  remarks: string | null;
  timecard_id: Generated<number>;
  type: string | null;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipTExtTimecardSystem {
  change_hour: number | null;
  create_date: Timestamp | null;
  end_hour: number | null;
  end_minute: number | null;
  outgoing_add_flag: string | null;
  resttime_in: number | null;
  resttime_out: number | null;
  start_day: number | null;
  start_hour: number | null;
  start_minute: number | null;
  system_id: Generated<number>;
  system_name: string | null;
  update_date: Timestamp | null;
  user_id: number;
  worktime_in: number | null;
  worktime_out: number | null;
}

export interface EipTExtTimecardSystemMap {
  create_date: Timestamp | null;
  system_id: number;
  system_map_id: Generated<number>;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipTMail {
  account_id: number;
  create_date: Timestamp | null;
  event_date: Timestamp | null;
  file_path: string | null;
  file_volume: number | null;
  folder_id: number;
  has_files: string | null;
  mail: Buffer | null;
  mail_id: Generated<number>;
  person: string | null;
  read_flg: string | null;
  subject: string | null;
  type: string | null;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipTMailFilter {
  account_id: number | null;
  create_date: Timestamp | null;
  dst_folder_id: number | null;
  filter_id: Generated<number>;
  filter_name: string | null;
  filter_string: string | null;
  filter_type: string | null;
  sort_order: number | null;
  update_date: Timestamp | null;
}

export interface EipTMailFolder {
  account_id: number | null;
  create_date: Timestamp | null;
  folder_id: Generated<number>;
  folder_name: string | null;
  update_date: Timestamp | null;
}

export interface EipTMemo {
  create_date: Timestamp | null;
  memo_id: Generated<number>;
  memo_name: string;
  note: string | null;
  owner_id: number;
  update_date: Timestamp | null;
}

export interface EipTMsgboardCategory {
  category_id: Generated<number>;
  category_name: string | null;
  create_date: Timestamp | null;
  note: string | null;
  owner_id: number | null;
  public_flag: string | null;
  update_date: Timestamp | null;
}

export interface EipTMsgboardCategoryMap {
  category_id: number | null;
  id: Generated<number>;
  status: string | null;
  user_id: number | null;
}

export interface EipTMsgboardFile {
  create_date: Timestamp | null;
  file_id: Generated<number>;
  file_name: string;
  file_path: string;
  file_thumbnail: Buffer | null;
  owner_id: number | null;
  topic_id: number | null;
  update_date: Timestamp | null;
}

export interface EipTMsgboardTopic {
  category_id: number | null;
  create_date: Timestamp | null;
  create_user_id: number | null;
  note: string | null;
  owner_id: number | null;
  parent_id: number | null;
  topic_id: Generated<number>;
  topic_name: string;
  update_date: Timestamp | null;
  update_user_id: number | null;
}

export interface EipTNote {
  accept_date: Timestamp | null;
  add_dest_type: string | null;
  client_name: string | null;
  company_name: string | null;
  create_date: Timestamp | null;
  custom_subject: string | null;
  email_address: string | null;
  message: string | null;
  note_id: Generated<number>;
  owner_id: string | null;
  subject_type: string | null;
  telephone: string | null;
  update_date: Timestamp | null;
}

export interface EipTNoteMap {
  confirm_date: Timestamp | null;
  del_flg: string | null;
  id: Generated<number>;
  note_id: number;
  note_stat: string | null;
  user_id: string;
}

export interface EipTReport {
  create_date: Timestamp | null;
  end_date: Timestamp | null;
  note: string | null;
  parent_id: number;
  report_id: Generated<number>;
  report_name: string | null;
  start_date: Timestamp | null;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipTReportFile {
  create_date: Timestamp | null;
  file_id: Generated<number>;
  file_name: string;
  file_path: string;
  file_thumbnail: Buffer | null;
  owner_id: number | null;
  report_id: number | null;
  update_date: Timestamp | null;
}

export interface EipTReportMap {
  create_date: Timestamp | null;
  id: Generated<number>;
  report_id: number;
  status: string | null;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipTReportMemberMap {
  id: Generated<number>;
  report_id: number;
  user_id: number;
}

export interface EipTSchedule {
  create_date: Timestamp | null;
  /**
   * 不使用
   */
  create_user_id: number | null;
  /**
   * 不使用
   */
  edit_flag: string | null;
  end_date: Timestamp | null;
  /**
   * 不使用
   */
  mail_flag: string | null;
  name: string | null;
  note: string | null;
  owner_id: number | null;
  parent_id: number | null;
  place: string | null;
  public_flag: string | null;
  repeat_pattern: string | null;
  schedule_id: Generated<number>;
  start_date: Timestamp | null;
  update_date: Timestamp | null;
  /**
   * 不使用
   */
  update_user_id: number | null;
}

export interface EipTScheduleMap {
  /**
   * 不使用
   */
  common_category_id: number;
  id: Generated<number>;
  schedule_id: number;
  /**
   * 不使用
   */
  status: string | null;
  type: string | null;
  user_id: number;
}

export interface EipTTimecard {
  create_date: Timestamp | null;
  reason: string | null;
  timecard_id: Generated<number>;
  update_date: Timestamp | null;
  user_id: number;
  work_date: Timestamp | null;
  work_flag: string;
}

export interface EipTTimecardSettings {
  create_date: Timestamp | null;
  end_hour: number | null;
  end_minute: number | null;
  resttime_in: number | null;
  resttime_out: number | null;
  start_hour: number | null;
  start_minute: number | null;
  timecard_settings_id: Generated<number>;
  update_date: Timestamp | null;
  user_id: number;
  worktime_in: number | null;
  worktime_out: number | null;
}

export interface EipTTimeline {
  app_id: string | null;
  create_date: Generated<Timestamp | null>;
  external_id: string | null;
  note: string | null;
  num_on_day: Generated<number | null>;
  owner_id: number | null;
  params: string | null;
  parent_id: Generated<number>;
  timeline_id: Generated<number>;
  timeline_type: string | null;
  update_date: Generated<Timestamp | null>;
}

export interface EipTTimelineFile {
  create_date: Timestamp | null;
  file_id: Generated<number>;
  file_name: string;
  file_path: string;
  file_thumbnail: Buffer | null;
  owner_id: number | null;
  timeline_id: number | null;
  update_date: Timestamp | null;
}

export interface EipTTimelineLike {
  create_date: Generated<Timestamp | null>;
  owner_id: number | null;
  timeline_id: number;
  timeline_like_id: Generated<number>;
}

export interface EipTTimelineMap {
  id: number;
  is_read: number | null;
  login_name: string;
  timeline_id: number | null;
}

export interface EipTTimelineUrl {
  body: string | null;
  thumbnail: Buffer | null;
  timeline_id: number | null;
  title: string | null;
  url: string;
  url_id: Generated<number>;
}

export interface EipTTodo {
  addon_schedule_flg: string;
  category_id: number | null;
  create_date: Timestamp | null;
  create_user_id: number;
  end_date: Timestamp | null;
  note: string | null;
  priority: number | null;
  public_flag: string;
  start_date: Timestamp | null;
  state: number | null;
  todo_id: Generated<number>;
  todo_name: string;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipTTodoCategory {
  category_id: Generated<number>;
  category_name: string;
  create_date: Timestamp | null;
  note: string | null;
  update_date: Timestamp | null;
  update_user_id: number;
  user_id: number;
}

export interface EipTWhatsnew {
  create_date: Timestamp | null;
  entity_id: number | null;
  parent_id: number | null;
  portlet_type: number | null;
  update_date: Timestamp | null;
  user_id: number | null;
  whatsnew_id: number;
}

export interface EipTWorkflowCategory {
  category_id: Generated<number>;
  category_name: string;
  create_date: Timestamp | null;
  note: string | null;
  route_id: number | null;
  template: string | null;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipTWorkflowFile {
  create_date: Timestamp | null;
  file_id: Generated<number>;
  file_name: string;
  file_path: string;
  file_thumbnail: Buffer | null;
  owner_id: number | null;
  request_id: number | null;
  update_date: Timestamp | null;
}

export interface EipTWorkflowRequest {
  category_id: number | null;
  create_date: Timestamp | null;
  note: string | null;
  parent_id: number | null;
  price: Int8 | null;
  priority: number | null;
  progress: string | null;
  request_id: Generated<number>;
  request_name: string | null;
  route_id: number | null;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipTWorkflowRequestMap {
  create_date: Timestamp | null;
  id: Generated<number>;
  note: string | null;
  order_index: number;
  request_id: number;
  status: string | null;
  update_date: Timestamp | null;
  user_id: number;
}

export interface EipTWorkflowRoute {
  create_date: Timestamp | null;
  note: string | null;
  route: string | null;
  route_id: Generated<number>;
  route_name: string;
  update_date: Timestamp | null;
}

export interface JetspeedGroupProfile {
  country: string | null;
  group_name: string | null;
  language: string | null;
  media_type: string | null;
  page: string | null;
  profile: Buffer | null;
  psml_id: number;
}

export interface JetspeedRoleProfile {
  country: string | null;
  language: string | null;
  media_type: string | null;
  page: string | null;
  profile: Buffer | null;
  psml_id: number;
  role_name: string | null;
}

export interface JetspeedUserProfile {
  country: string | null;
  language: string | null;
  media_type: string | null;
  page: string | null;
  profile: Buffer | null;
  psml_id: number;
  user_name: string | null;
}

export interface ModuleId {
  id: number;
}

export interface OauthConsumer {
  app_id: number | null;
  consumer_key: string | null;
  consumer_secret: string | null;
  create_date: Timestamp | null;
  id: number;
  name: string | null;
  type: string | null;
  update_date: Timestamp | null;
}

export interface OauthEntry {
  app_id: string | null;
  authorized: number | null;
  callback_token: string | null;
  callback_token_attempts: number | null;
  callback_url: string | null;
  callback_url_signed: number | null;
  consumer_key: string | null;
  container: string | null;
  domain: string | null;
  id: number;
  issue_time: Timestamp | null;
  oauth_version: string | null;
  token: string | null;
  token_secret: string | null;
  type: string | null;
  user_id: string | null;
}

export interface OauthToken {
  access_token: string | null;
  id: number;
  session_handle: string | null;
  token_expire_milis: number | null;
  token_secret: string | null;
}

export interface OripoPages {
  created_at: Generated<Timestamp>;
  is_default: Generated<boolean>;
  layout: Generated<string>;
  page_id: Generated<number>;
  page_name: string;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface OripoPageWidgets {
  col: Generated<number>;
  created_at: Generated<Timestamp>;
  page_id: number;
  row: Generated<number>;
  updated_at: Generated<Timestamp>;
  widget_id: Generated<number>;
  widget_type: string;
}

export interface OripoSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  ip_addr: string | null;
  session_id: string;
  user_id: number;
}

export interface TurbineGroup {
  group_alias_name: string | null;
  group_id: Generated<number>;
  group_name: string;
  /**
   * 不使用
   */
  objectdata: Buffer | null;
  owner_id: number | null;
  public_flag: string | null;
}

export interface TurbinePermission {
  objectdata: Buffer | null;
  permission_id: Generated<number>;
  permission_name: string;
}

export interface TurbineRole {
  /**
   * 不使用
   */
  objectdata: Buffer | null;
  role_id: Generated<number>;
  role_name: string;
}

export interface TurbineRolePermission {
  permission_id: number;
  role_id: number;
}

export interface TurbineUser {
  /**
   * 不使用
   */
  cellular_mail: string | null;
  cellular_phone: string | null;
  /**
   * 不使用
   */
  cellular_uid: string | null;
  /**
   * 不使用
   */
  company_id: number | null;
  confirm_value: string | null;
  created: Timestamp | null;
  created_user_id: number | null;
  disabled: string | null;
  /**
   * 不使用
   */
  email: string | null;
  first_name: string;
  first_name_kana: string | null;
  /**
   * 不使用
   */
  has_photo: Generated<string | null>;
  /**
   * 不使用
   */
  has_photo_smartphone: Generated<string | null>;
  /**
   * 不使用
   */
  in_telephone: string | null;
  last_login: Timestamp | null;
  last_name: string;
  last_name_kana: string | null;
  login_name: string;
  modified: Timestamp | null;
  /**
   * 不使用
   */
  objectdata: Buffer | null;
  /**
   * 不使用
   */
  out_telephone: string | null;
  password_changed: Timestamp | null;
  password_value: string;
  /**
   * 不使用
   */
  photo: Buffer | null;
  /**
   * 不使用
   */
  photo_modified: Timestamp | null;
  /**
   * 不使用
   */
  photo_modified_smartphone: Timestamp | null;
  /**
   * 不使用
   */
  photo_smartphone: Buffer | null;
  /**
   * 不使用
   */
  position_id: number | null;
  /**
   * 不使用
   */
  tutorial_forbid: Generated<string | null>;
  updated_user_id: number | null;
  user_id: Generated<number>;
}

export interface TurbineUserGroupRole {
  group_id: number;
  id: Generated<number>;
  role_id: number;
  user_id: number;
}

export interface DB {
  activity: Activity;
  activity_map: ActivityMap;
  aipo_license: AipoLicense;
  app_data: AppData;
  application: Application;
  container_config: ContainerConfig;
  eip_facility_group: EipFacilityGroup;
  eip_m_address_group: EipMAddressGroup;
  eip_m_addressbook: EipMAddressbook;
  eip_m_addressbook_company: EipMAddressbookCompany;
  eip_m_company: EipMCompany;
  eip_m_config: EipMConfig;
  eip_m_facility: EipMFacility;
  eip_m_facility_group: EipMFacilityGroup;
  eip_m_facility_group_map: EipMFacilityGroupMap;
  eip_m_inactive_application: EipMInactiveApplication;
  eip_m_mail_account: EipMMailAccount;
  eip_m_mail_notify_conf: EipMMailNotifyConf;
  eip_m_position: EipMPosition;
  eip_m_post: EipMPost;
  eip_m_user_position: EipMUserPosition;
  eip_t_acl_map: EipTAclMap;
  eip_t_acl_portlet_feature: EipTAclPortletFeature;
  eip_t_acl_role: EipTAclRole;
  eip_t_acl_user_role_map: EipTAclUserRoleMap;
  eip_t_addressbook_group_map: EipTAddressbookGroupMap;
  eip_t_blog: EipTBlog;
  eip_t_blog_comment: EipTBlogComment;
  eip_t_blog_entry: EipTBlogEntry;
  eip_t_blog_file: EipTBlogFile;
  eip_t_blog_footmark_map: EipTBlogFootmarkMap;
  eip_t_blog_thema: EipTBlogThema;
  eip_t_cabinet_file: EipTCabinetFile;
  eip_t_cabinet_folder: EipTCabinetFolder;
  eip_t_cabinet_folder_map: EipTCabinetFolderMap;
  eip_t_common_category: EipTCommonCategory;
  eip_t_eventlog: EipTEventlog;
  eip_t_ext_timecard: EipTExtTimecard;
  eip_t_ext_timecard_system: EipTExtTimecardSystem;
  eip_t_ext_timecard_system_map: EipTExtTimecardSystemMap;
  eip_t_mail: EipTMail;
  eip_t_mail_filter: EipTMailFilter;
  eip_t_mail_folder: EipTMailFolder;
  eip_t_memo: EipTMemo;
  eip_t_msgboard_category: EipTMsgboardCategory;
  eip_t_msgboard_category_map: EipTMsgboardCategoryMap;
  eip_t_msgboard_file: EipTMsgboardFile;
  eip_t_msgboard_topic: EipTMsgboardTopic;
  eip_t_note: EipTNote;
  eip_t_note_map: EipTNoteMap;
  eip_t_report: EipTReport;
  eip_t_report_file: EipTReportFile;
  eip_t_report_map: EipTReportMap;
  eip_t_report_member_map: EipTReportMemberMap;
  eip_t_schedule: EipTSchedule;
  eip_t_schedule_map: EipTScheduleMap;
  eip_t_timecard: EipTTimecard;
  eip_t_timecard_settings: EipTTimecardSettings;
  eip_t_timeline: EipTTimeline;
  eip_t_timeline_file: EipTTimelineFile;
  eip_t_timeline_like: EipTTimelineLike;
  eip_t_timeline_map: EipTTimelineMap;
  eip_t_timeline_url: EipTTimelineUrl;
  eip_t_todo: EipTTodo;
  eip_t_todo_category: EipTTodoCategory;
  eip_t_whatsnew: EipTWhatsnew;
  eip_t_workflow_category: EipTWorkflowCategory;
  eip_t_workflow_file: EipTWorkflowFile;
  eip_t_workflow_request: EipTWorkflowRequest;
  eip_t_workflow_request_map: EipTWorkflowRequestMap;
  eip_t_workflow_route: EipTWorkflowRoute;
  jetspeed_group_profile: JetspeedGroupProfile;
  jetspeed_role_profile: JetspeedRoleProfile;
  jetspeed_user_profile: JetspeedUserProfile;
  module_id: ModuleId;
  oauth_consumer: OauthConsumer;
  oauth_entry: OauthEntry;
  oauth_token: OauthToken;
  oripo_page_widgets: OripoPageWidgets;
  oripo_pages: OripoPages;
  oripo_sessions: OripoSessions;
  turbine_group: TurbineGroup;
  turbine_permission: TurbinePermission;
  turbine_role: TurbineRole;
  turbine_role_permission: TurbineRolePermission;
  turbine_user: TurbineUser;
  turbine_user_group_role: TurbineUserGroupRole;
}
